basePath: /products
consumes:
- application/json
definitions:
  Product:
    properties:
      description:
        type: string
        x-go-name: Description
      id:
        format: int64
        type: integer
        x-go-name: Id
      name:
        type: string
        x-go-name: Name
      price:
        format: float
        type: number
        x-go-name: Price
      sku:
        type: string
        x-go-name: Sku
    type: object
    x-go-package: data
host: localhost:9090
info:
  description: |-
    Package classification of ProductsHandler
    Language: go
    Documentation for Product API
  version: 1.0.0
paths:
  /products:
    get:
      description: Returns a list of products
      operationId: GetProducts
      responses:
        "200":
          $ref: '#/responses/productsResponse'
      tags:
      - Products
produces:
- application/json
responses:
  productsResponse:
    description: This method is not used into the logic of the application, but is
      used to create the swagger documentation response
    schema:
      items:
        $ref: '#/definitions/Product'
      type: array
schemes:
- http
swagger: "2.0"
