basePath: /products
consumes:
- application/json
definitions:
  Product:
    description: Product defines the structure of a product
    properties:
      description:
        description: Description of the product
        type: string
        x-go-name: Description
      id:
        description: Product ID
        example: 1
        format: int64
        type: integer
        x-go-name: Id
      name:
        description: Name of the product
        type: string
        x-go-name: Name
      price:
        description: Price of the product
        example: 9.99
        format: float
        type: number
        x-go-name: Price
      sku:
        description: SKU of the product
        example: '`^[a-z]+-[0-9]+$`'
        type: string
        x-go-name: Sku
    required:
    - name
    - description
    - price
    - sku
    type: object
    x-go-package: data
host: localhost:9090
info:
  description: |-
    Package classification of ProductsHandler
    Language: go
    Documentation for Product API
  version: 1.0.0
paths:
  /products:
    get:
      description: Returns a list of products
      operationId: GetProducts
      responses:
        "200":
          $ref: '#/responses/productsResponse'
      tags:
      - Products
    post:
      description: Creates a new product
      operationId: CreateProduct
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/Product'
      responses:
        "201":
          $ref: '#/responses/productsCreatedResponse'
      tags:
      - Products
produces:
- application/json
responses:
  productsResponse:
    description: ""
    schema:
      items:
        $ref: '#/definitions/Product'
      type: array
schemes:
- http
swagger: "2.0"
